### ISSUE TITLE
Why is there not a queue set here  / URLSession(configuration: configuration, delegate: self, delegateQueue: nil)

### ISSUE THREAD

**Issue by 8secz-johndpope** [sukov/CachingPlayerItem#1]
session = URLSession(configuration: configuration, delegate: self, delegateQueue: nil) ???

and why not use AVAssetDownloadURLSession
https://developer.apple.com/documentation/avfoundation/avassetdownloadurlsession
instead of URLSession ?

**Comment by sukov** [comment]
There is no need for queue to be set, please read Apple's docs first before opening an issue https://developer.apple.com/documentation/foundation/urlsession/1411597-init.

Which benefit does AVAssetDownloadURLSession have over the URLSession in this case?

**Comment by 8secz-johndpope** [comment]
ok thanks - 
not actually sure if AVAssetDownloadURLSession is of use - seems to be available in later os - thought it may supercede older code
