### ISSUE TITLE
Does it work well with URL with Parameters

### ISSUE THREAD

**Issue by Xenolion** [sukov/CachingPlayerItem#10]
For instance the URL looks like `https://ddomain.com/myfile.mp4?token=adajah828hhy297`
Will the player play it and cache it in such a way that even if the token changes it will still refer to the same file locally?

**Comment by sukov** [comment]
Hello @Xenolion,

If the file is fully downloaded (cached) the token is no longer relevant and the file will be accessed from the local disc.

**Comment by Xenolion** [comment]
The question is if the file was partially downloaded can I resume playing it tomorrow? using a link with a different token. Or should I start downloading it from the beginning?

**Comment by Xenolion** [comment]
Does it resume the same file download when played at a later time? @sukov

**Comment by sukov** [comment]
Nope, resuming is currently not supported.
