### ISSUE TITLE
Large video does not start playing after download finishes

### ISSUE THREAD

**Issue by gajddo00** [sukov/CachingPlayerItem#12]
## Issue
Hello! Thanks for the great snippet.
I've been struggling with figuring out why a large video (300MB) does not play after it's downloaded. Smaller size videos (10MB even 100MB) play fine. The video is a basic mp4 without moov item in the beginning so they have to be completely downloaded before they start playing. The larger video downloads successfully but then the player is stuck in waitingToPlayAtSpecifiedRate with reason noItemToPlay. Any ideas of what might be the problem?

I'm referring to caching initializers. It also takes way longer than regular AVPlayerItem to play if it's the caching case basically only stars playing when the entire file is downloaded while AVPlayerItem starts playing way way sooner.

## Example
[Here's](https://secret-memories.3a0e8493c00fa2487b71580016cad807.r2.cloudflarestorage.com/user-videos/acb364b0-e096-4f2e-8a79-b44eaf240686_clean_video_s3_key.mp4?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=c7aa518caffdd78ea3544d5f64202a33%2F20231116%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231116T145450Z&X-Amz-Expires=86400&X-Amz-Signature=d39d1f0963c886b623397716a21a064b6dac308b3e868d05fadf490be9ebe712&X-Amz-SignedHeaders=host) the video url for reference.

## Environment
iOS 17.0.1
Xcode 15.0.1

Thanks a lot!

**Comment by chindoo** [comment]
Hello, thanks a lot the lib.

I am having the same issue but with a small size video less than 3MO.
When first time downloading the video, it does not start automatically after download.
I had to do a workaround to make it work.

This is my code in the configure method of my collectionView cell:

`videoModel = ModelVideoProperties(
            id: String(videoURL.absoluteString.md5()),
            streamURL: videoURL,
            fileExtension: videoURL.pathExtension
        )`

`if let player = player, let videoModel {
            let newPlayerItem = CachingPlayerItem(model: videoModel)
            playerItem.delegate = self
            looper = AVPlayerLooper(player: player, templateItem: newPlayerItem)
            player.play()
        }`

And this is the delegate:

`func playerItem(_ playerItem: CachingPlayerItem, didFinishDownloadingFileAt filePath: String) {
        guard let videoModel, let player else {
            return
        }
        
        let playerItem = CachingPlayerItem(model: videoModel)
        looper = AVPlayerLooper(player: player, templateItem: playerItem)
        player.play()
    }`

That is what I had to do wich is not a clean way to do the desired job.

If you have a suggestion please let us know.

PS: Xcode 15.0.1
iOS: 14.1

Thanks again.

**Comment by gajddo00** [comment]
Hey! 
I haven't been able to solve this but this probably has to do with the API (AVPlayer) more than the way this lib is written. I ended up listening for the download finish and then if the video still hasn't started playing I just replace the current player item. I suppose the progressive download has to do with mp4 videos that don't have the correct moov item placement. Apple's AVPlayerItem implementation has to do something more sophisticated as the videos load much faster even if they're not completely downloaded but I'm not sure that can be even done with the AVAssetResourceLoader.
