### ISSUE TITLE
Sometimes, it crashes from the processPendingRequest function.

### ISSUE THREAD

**Issue by istsest** [sukov/CachingPlayerItem#13]
It happens very sometimes to get crash from the processPendingRequest function.
looks like unsafe-thread.

<img width="1912" alt="Screenshot 2023-12-04 at 9 16 45 AM" src="https://github.com/sukov/CachingPlayerItem/assets/4244671/b7c893f4-407f-4d62-a1d2-0815f4fda4a1">

**Comment by krayc425** [comment]
Ran into the same issue

**Comment by chenhaifeng111** [comment]
my project  also crash

**Comment by chenhaifeng111** [comment]
@sukov can you resolve the crash

**Comment by chenhaifeng111** [comment]
> Ran into the same issue

do you resolve it

**Comment by sukov** [comment]
Hey, thank you for reporting this issue. If possible please do share repro steps and more information

**Comment by chenhaifeng111** [comment]
> Hey, thank you for reporting this issue. If possible please do share repro steps and more information

**Comment by chenhaifeng111** [comment]
Fatal Exception: NSInvalidArgumentException
-[NSTaggedPointerString countByEnumeratingWithState:objects:count:]: unrecognized selector sent to instance 0x8000000000000000
0
CoreFoundation
__exceptionPreprocess
5
libswiftCore.dylib
__CocoaSet.Iterator.next()
6
Enjoy
ResourceLoaderDelegate.swift - 第 156 行
specialized Set._Variant.filter(_:) + 156
7
Enjoy
ResourceLoaderDelegate.swift - 第 121 行
specialized ResourceLoaderDelegate.urlSession(_:dataTask:didReceive:) + 121
8
Enjoy
<compiler-generated>
@objc ResourceLoaderDelegate.urlSession(_:dataTask:didReceive:)
9
Enjoy
FPRNSURLSessionDelegateInstrument.m - 第 122 行
__InstrumentURLSessionDataTaskDidReceiveData_block_invoke + 122
10
CFNetwork
CFHostCreateCopy
18
libsystem_pthread.dylib
start_wqthread

**Comment by chenhaifeng111** [comment]
![image](https://github.com/user-attachments/assets/1ff9606d-4d61-47dc-b384-76130683057d)
@sukov

**Comment by sukov** [comment]
Fixed on the latest release, use version 1.1.1
