### ISSUE TITLE
mux.com integration

### ISSUE THREAD

**Issue by drsounds** [sukov/CachingPlayerItem#16]
I am trying to use this with my app that consumes m3u video streams from mux.com but it doesn't work

````
CachingPlayerItem status: failed with error: Optional(Error Domain=NSURLErrorDomain Code=-1008 "resource unavailable"
````

With regular AVPlayerItem it works as usual

**Comment by sukov** [comment]
Hello @drsounds. Unfortunately **M3U8**  is not currently supported as it requires a local proxy server for playing the downloaded media. You are welcome to contribute with adding that functionality to this repo. Meanwhile here is a library that serves for that https://github.com/WillieWangWei/WLM3U.
