### ISSUE TITLE
When using UICollectionView, it happens when the page switches.

### ISSUE THREAD

**Issue by pasmall** [sukov/CachingPlayerItem#17]
![WeChat18a2fcbe3c5c812dd401f80e43757a1e](https://github.com/user-attachments/assets/f5c1cafe-6bbf-4f20-87e5-c016105875ca)
Can you help me?

**Comment by sukov** [comment]
Are you using the latest version? Could you please include the stack trace?

**Comment by pasmall** [comment]
used 1.1.1 ,Occurs when the item is destroyed
![WeChatf3fdfc7711dba7fc78961947c9055825](https://github.com/user-attachments/assets/d6056e68-a2c3-4cfb-90a1-06b6f0ca2af5)

**Comment by sukov** [comment]
This issue is fixed on the latest version (1.1.3). Please update and once you confirm close this issue.

**Comment by pasmall** [comment]
Thank you very much, it helped a lot
