### ISSUE TITLE
Sometimes there is an error loading local files

### ISSUE THREAD

**Issue by pasmall** [sukov/CachingPlayerItem#18]
Playing from cached local file.
CachingPlayerItem status: failed with error: Optional(Error Domain=AVFoundationErrorDomain Code=-11849 "操作已停止" UserInfo={NSLocalizedFailureReason=此媒体可能已损坏。, NSLocalizedDescription=操作已停止, NSUnderlyingError=0x301dd6280 {Error Domain=NSOSStatusErrorDomain Code=-12873 "(null)"}})

**Comment by sukov** [comment]
It seems that your local file might be corrupted or you are not using the correct extension. Check [Apple docs](https://developer.apple.com/documentation/avfoundation/averror/code/failedtoloadmediadata/). Please try using the native `AVPlayerItem` instead to verify that the error is not related to this library.
