### ISSUE TITLE
Download function not working

### ISSUE THREAD

**Issue by argie-w** [sukov/CachingPlayerItem#20]
Hi, this is very useful code to me, however, when calling playerItem.download() to pre download the file the download session never starts. Not sure what I am doing wrong. Everything works just fine when after loading the playerItem into AVPlayer, caching works normally. 

I have tried following the code, there are no errors thrown, after startDataRequest(with url: url) nothing happens.

**Comment by sukov** [comment]
Hey there. It is very hard to diagnose the issue without the actual code provided, but my educated guess would be that you are not holding a strong reference to the CachingPlayerItem instance when pre-downloading.
