### ISSUE TITLE
crash related to `ResourceLoaderDelegate.pendingRequests`

### ISSUE THREAD

**Issue by AndrewSB** [sukov/CachingPlayerItem#24]
hey, noticed this crash. not sure how to reproduce this locally, but it seems to happen somewhat regularly

<img width="1267" alt="Screenshot 2024-12-09 at 11 57 46 AM" src="https://github.com/user-attachments/assets/24edcd40-9c19-4536-b5ef-889de4e18be1">

maybe related to https://github.com/sukov/CachingPlayerItem/issues/13 ? i'm not sure

**Comment by AndrewSB** [comment]
this is what an LLM says to do:

Let me help you analyze this code snippet. The potential issue here is with the way you're using the setter for `pendingRequests`.

The problem lies in the asynchronous setter with a barrier flag. When you use `queue.async(flags: .barrier)`, you're scheduling the assignment to happen asynchronously, which means the setter will return immediately without waiting for the assignment to complete. This can lead to a race condition and unexpected behavior.

Specifically, this can crash or cause issues because:

1. The setter is marked as `async`, but the property itself isn't defined as an async property.
2. The weak reference capture could potentially cause the assignment to be skipped if `self` is deallocated.
3. There's no synchronization mechanism to ensure the new value is actually set before other parts of the code might access `pendingRequests`.

A safer approach would be to use a synchronous barrier operation:

```swift
private var pendingRequests: Set<AVAssetResourceLoadingRequest> {
    get { queue.sync { return pendingRequestsValue } }
    set { queue.sync(flags: .barrier) { [weak self] in self?.pendingRequestsValue = newValue } }
}
```

Key changes:
- Changed `async` to `sync` with `.barrier` flag
- This ensures the assignment happens atomically and synchronously
- Prevents potential race conditions
- Ensures the new value is set before any other operations can access the property

If you need asynchronous behavior, you might want to consider using a more explicit async method or restructuring how you manage these pending requests.

**Comment by sukov** [comment]
@AndrewSB thank you for reporting this issue. I've changed the entire logic regarding the pending requests on `ResourceLoaderDelegate` in the latest version of this pod `2.0.1` and this logic is no longer present for "thread safe array". I would suggest to you to update to the latest one and let me know if there are any similar issues.

**Comment by AndrewSB** [comment]
oh my mistake, i'm on 1.1.3. let me update. i'll reopen if this is still an issue
