### ISSUE TITLE
Crash for init CachingPlayerItem

### ISSUE THREAD

**Issue by mmrobert** [sukov/CachingPlayerItem#6]
Crash when init CachingPlayerItem: CachingPlayerItem(url: url):

CachingPlayerItem/CachingPlayerItem.swift:185: Fatal error: CachingPlayerItem error: init(asset:automaticallyLoadedAssetKeys:) not implemented

I checked the code base, different places call the super.init, not this one.

**Comment by sukov** [comment]
@mmrobert I see what's going on, thank you for reporting this I will fix it when I have the time. For now please use `CachingPlayerItem(url: url, avUrlAssetOptions: nil)`

**Comment by mmrobert** [comment]
Thanks
    On Wednesday, February 8, 2023 at 06:30:43 AM PST, Gorjan Shukov ***@***.***> wrote:  
 
 


@mmrobert I see what's going on, thank you for reporting this I will fix it when I have the time. For now please call CachingPlayerItem(url: url, avUrlAssetOptions: nil)

**Comment by sukov** [comment]
Fixed in the latest release [1.0.7](https://github.com/sukov/CachingPlayerItem/releases/tag/1.0.7)
