### ISSUE TITLE
Still got crash when play with AVPlayerLooper

### ISSUE THREAD

**Issue by hungnguyen1791** [sukov/CachingPlayerItem#8]
Using CachingPlayerItem with code like this will make the crash happen
`
      let url = URL(string: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4")!
        let playerItem = CachingPlayerItem(url: url, avUrlAssetOptions: nil)

        let queuePlayer = AVQueuePlayer(playerItem: playerItem)

        // Create a new player looper with the queue player and template item
        self.avPlayerLooper = AVPlayerLooper(player: queuePlayer, templateItem: playerItem)

        let playerLayer = AVPlayerLayer(player: queuePlayer)
        playerLayer.frame = self.view.bounds
        playerLayer.videoGravity = .resizeAspect
        self.view.layer.addSublayer(playerLayer)

        queuePlayer.play()
`
<img width="1421" alt="Screen Shot 2023-05-30 at 08 59 15" src="https://github.com/sukov/CachingPlayerItem/assets/91858465/417f9ba0-3553-4a18-b149-7a27670079ab">

[DemoCrash.zip](https://github.com/sukov/CachingPlayerItem/files/11595008/DemoCrash.zip)

**Comment by hungnguyen1791** [comment]
Hi @sukov
I raise this [PR](https://github.com/sukov/CachingPlayerItem/pull/9) to solve the above issue, it works fine on my project now. Please help to review, merge, and release a new version if possible. Thanks

**Comment by sukov** [comment]
Thank you for raising awareness about this issue. Fixed in `1.0.8`.
